## Logic to Karnaugh map

[Wiki: Karnaugh map](https://en.wikipedia.org/wiki/Karnaugh_map)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/K-map_6%2C8%2C9%2C10%2C11%2C12%2C13%2C14_anti-race.svg/440px-K-map_6%2C8%2C9%2C10%2C11%2C12%2C13%2C14_anti-race.svg.png)

In [26]:
from sympy.combinatorics.graycode import GrayCode
from itertools import permutations
import numpy as np

In [27]:
def ReverseBinCode(l):
    # Generate reversed binary code for pyphi
    maxIndex = 2 ** l - 1
    return [np.binary_repr(maxIndex - index, width=l) for index in range(2 ** l)]

## 输入`pyphi`中状态转移矩阵，给出各个变量的卡诺图

In [3]:
# 输入状态转移列表，给出各个量的卡诺图矩阵

def MapToKarnaughMap(_map):
    # Turn map to MapToKarnaugh Maps
    # Generate ReverseBinCode
    index = ReverseBinCode(len(_map[0]))
    #index = np.array([[int(char) for char in strcode] for strcode in index])
    
    dim1 = (int(len(_map[0]) / 2))
    dim2 = (len(_map[0]) - int(len(_map[0]) / 2))
    #print('dim =', dim1, 'x', dim2)
    
    gc1 = GrayCode(dim1)
    gc2 = GrayCode(dim2)
    gd1 = dict(zip(list(gc1.generate_gray()), range(2 ** dim1)))
    gd2 = dict(zip(list(gc2.generate_gray()), range(2 ** dim2)))
    #print(gd1)
    #print(gd2)
    
    _map = np.array(_map).T
    KarnaughMaps = []
    for targetStates in _map:
        #print('-------')
        Karnaugh = np.array(([[0] * (2 ** dim1)]) * (2 ** dim2)).T
        #print(Karnaugh)
        for state, mcode in zip(index, targetStates):
            #print(state, '->', mcode)
            #print('c1=',state[0:dim1])
            #print('c2=',state[dim1:])
            Karnaugh[gd1[state[0:dim1]], gd2[state[dim1:]]] = mcode
        KarnaughMaps += [Karnaugh]
        #print(Karnaugh)
    
    return np.array(KarnaughMaps)

## 输入矩阵，给出Ising模型能量

In [4]:
def IsingEnergy(mat, energy={0:-1, 1:1}):
    # 给出mat的Ising能量
    # Return Ising energy of mat
    mat = np.array(mat)
    # If mat is a list of mat, then return all energy
    if len(mat.shape) == 3:
        return np.array([IsingEnergy(_mat, energy) for _mat in mat])
    # Otherwise return this energy
    x, y = mat.shape
    total_E = 0
    for i in range(x):
        for j in range(y):
            total_E += energy[mat[i][j]] * energy[mat[(i - 1) % x][j]]
            total_E += energy[mat[i][j]] * energy[mat[(i + 1) % x][j]]
            total_E += energy[mat[i][j]] * energy[mat[i][(j - 1) % y]]
            total_E += energy[mat[i][j]] * energy[mat[i][(j + 1) % y]]
    return -total_E

In [57]:
m = [
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]
    ]
MapToKarnaughMap(m)

array([[[1, 1, 1, 1],
        [0, 0, 0, 0]],

       [[1, 1, 0, 0],
        [1, 1, 0, 0]],

       [[1, 0, 0, 1],
        [1, 0, 0, 1]]])

## 对状态名重新标记 Relabel

In [6]:
testorder=permutations(m).__next__()

In [106]:
def code2str(codeList):
    s = ''
    for i in codeList:
        s += str(i)
    return s

def relabel(m0, order):
    length = len(m0[0])
    bcode = ReverseBinCode(length)
    reorderRule = {}
    for originLabel, newLabel in zip(bcode, order):
        reorderRule[originLabel] = newLabel
    #print(reorderRule)
    rule = {}
    for currentState, nextState in zip(bcode, m0):
        #print(reorderRule[code2str(currentState)], 'to', str(nextState))
        rule[code2str(reorderRule[code2str(currentState)])] = reorderRule[code2str(nextState)]
    
    new_m = [rule[startState] for startState in ReverseBinCode(length)]
    
    return np.array(new_m)

In [107]:
print(relabel(m, testorder))

NameError: name 'testorder' is not defined

In [43]:
MapToKarnaughMap(relabel(testM, testOrder))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [1, 0]]])

## 计算不同排序的Ising能量

In [54]:
m = [
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]
    ]
energyList = []
maxlen = 50

testorders=permutations(m)

for i, order in zip(range(maxlen), testorders):
    current_m = relabel(m, list(order))
    energy = [IsingEnergy(kmap) for kmap in MapToKarnaughMap(current_m)]
    energyList += energy

print(energyList)

[0, -16, -16, 0, -16, 32, 0, -16, -16, 0, 8, 8, 0, 8, 8, 0, 32, -16, 0, -16, 32, 0, -16, -16, 0, 8, 8, 0, 0, -16, 0, 16, 16, 0, 8, 8, 0, 8, 8, 0, 16, 16, 0, 32, -16, 0, 8, 8, 0, -16, -16, 0, -16, 0, 0, 0, -16, 0, 8, 8, 0, 8, 8, 0, -16, -16, 0, -16, 0, 0, -16, -16, 0, -16, -16, 0, -16, 32, 0, -16, -16, 0, 8, 8, 0, 8, 8, 0, 32, -16, -16, 0, -16, -16, 0, 32, 0, 0, 0, 8, 0, 8, 0, 16, 16, 8, 16, -16, 0, 0, 0, 0, 16, 16, -16, -16, 0, 8, -16, 16, -16, 32, 0, 8, 8, 0, 8, 0, 8, 8, 16, -16, 8, -16, 16, 32, -16, -16, 8, 8, 0, 32, -16, -16, 0, -16, 32, 0, -16, -16]


## NN for learning dynamic of network

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data as data
import torch.optim as optim

In [6]:
class net(nn.Module):
    def __init__(self, size_vis, size_hidden):
        super(net, self).__init__()
        self.fcn_v = nn.Linear(size_vis, size_vis)
        self.fcn_v2h = nn.Linear(size_vis, size_hidden)
        self.fcn_h2v = nn.Linear(size_hidden, size_vis)
        
    def forward(self, x):
        h = torch.sigmoid(self.fcn_v2h(x))
        xp = torch.sigmoid(self.fcn_v(x))
        
        xout = torch.sigmoid(self.fcn_h2v(h) + self.fcn_v(xp))
        
        return xout

In [7]:
IITnet = net(3, 4)

In [8]:
IITnet.forward(torch.Tensor([0,0,0]))

tensor([0.4163, 0.6362, 0.3800], grad_fn=<SigmoidBackward>)

In [34]:
m = [
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]
    ]

In [33]:
def BinCodeList(length):
    s = ReverseBinCode(length)

    return [[int(char) for char in ss] for ss in s]

class graphData(data.Dataset):
    def __init__(self, _m):
        super(graphData, self).__init__()
        self.inputs = BinCodeList(len(m[0]))
        self.m = _m
        
    def __len__(self):
        return len(self.inputs)
    def __getitem__(self, index):
        return self.inputs[index], self.m[index]

In [93]:
IITnet = net(3, 4)



dataset = graphData(m)
setLoader = data.DataLoader(dataset, batch_size = 1)
optimizer = optim.SGD(IITnet.parameters(), lr = 0.01, momentum=0.9, weight_decay=0.0005)

loss_fn = torch.nn.MSELoss()

for epco in range(4000):
    for inputdata, target in setLoader:
        optimizer.zero_grad()
        output = IITnet.forward(torch.Tensor(inputdata))
        loss = loss_fn(output, torch.Tensor(target))
        loss.backward()
        optimizer.step()
    if epco % 400 == 0:
        print('epco', epco, 'loss:',loss.item())

epco 0 loss: 0.22029556334018707
epco 400 loss: 0.08167281746864319
epco 800 loss: 0.021813470870256424
epco 1200 loss: 0.014217870309948921
epco 1600 loss: 0.012218523770570755
epco 2000 loss: 0.011513054370880127
epco 2400 loss: 0.011218958534300327
epco 2800 loss: 0.011076707392930984
epco 3200 loss: 0.010997287929058075
epco 3600 loss: 0.010946993716061115


In [102]:
def trainNet(_m):
    _IITnet = net(3, 4)

    dataset = graphData(_m)
    setLoader = data.DataLoader(dataset, batch_size = 1)
    optimizer = optim.SGD(_IITnet.parameters(), lr = 0.01, momentum=0.9, weight_decay=0.0005)

    loss_fn = torch.nn.MSELoss()

    for epco in range(1400):
        for inputdata, target in setLoader:
            optimizer.zero_grad()
            output = _IITnet.forward(torch.Tensor(inputdata))
            loss = loss_fn(output, torch.Tensor(target))
            loss.backward()
            optimizer.step()
        #if epco % 400 == 0:
            #print('epco', epco, 'loss:',loss.item())
    return _IITnet

In [145]:
trainNet(m)

net(
  (fcn_v): Linear(in_features=3, out_features=3, bias=True)
  (fcn_v2h): Linear(in_features=3, out_features=4, bias=True)
  (fcn_h2v): Linear(in_features=4, out_features=3, bias=True)
)

In [104]:
testorders=permutations(m)

energylist = []

for i,ms in zip(range(5),testorders):
    energylist += [ms, [NetEnergy(trainNet(ms)) for j in range(3)]]

print(energylist)

[([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]), [113.74878692626953, 112.23719024658203, 112.02633666992188], ([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 1], [1, 1, 0]), [99.32850646972656, 101.95207214355469, 92.23348999023438], ([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 1, 0], [1, 0, 1], [1, 1, 1]), [109.4934310913086, 68.52285766601562, 69.92340850830078], ([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 1, 0], [1, 1, 1], [1, 0, 1]), [98.31291198730469, 112.57115936279297, 122.3484115600586], ([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 1, 1], [1, 0, 1], [1, 1, 0]), [103.64986419677734, 101.21601867675781, 93.5998306274414]]


In [88]:
NetEnergy(IITnet)

111.48381042480469

In [87]:
def NetEnergy(net):
    totalEnergy = 0.0
    for para in net.parameters():
        flat_para = para.view(para.numel())
        totalEnergy += sum(flat_para * flat_para)
    
    return totalEnergy.item()

In [105]:
len(list(testorders))

40315

In [108]:
m

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

In [124]:
check = {}
for order in permutations(m):
    check[str(relabel(m, order))] = relabel(m, order)

In [127]:
def AllLabelConfigurations(mat):
    # 返回所有可能的重标记方法
    _check = {}
    for order in permutations(mat):
        _check[str(relabel(mat, order))] = relabel(mat, order)
    return list(_check.values())

In [129]:
len(AllLabelConfigurations(m))

105

In [130]:
all_labels = AllLabelConfigurations(m)

In [161]:
NetEnergy(trainNet(all_labels[0].tolist()))

125.50801086425781